name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        triplet: [x86-windows, x64-windows]
        include:
          - triplet: x86-windows
            system: windows-latest
          - triplet: x64-windows
            system: windows-latest
    runs-on: ${{ matrix.system }}
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install CMake
      uses: lukka/get-cmake@latest
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: c01dc6ea7353758f2ed70df0bc29c97dfc650b3a
    - name: 'Setup NuGet/Vcpkg Credentials'
      working-directory: ${{steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT}}
      shell: 'bash'
      run: >
        `vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/rioki/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "rioki" \
          -password "${{ secrets.VCPKG_PAT_TOKEN }}"
        `vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ secrets.VCPKG_PAT_TOKEN }}" \
          -source "https://nuget.pkg.github.com/rioki/index.json"
    - name: Build Debug
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-debug'
        buildPreset: 'ninja-debug'
    - name: Build Release
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-release'
        buildPreset: 'ninja-release'
