name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        triplet: [x86-windows, x64-windows]
        include:
          - triplet: x86-windows
            system: windows-latest
            mono: ""
          - triplet: x64-windows
            system: windows-latest
            mono: ""
          - triplet: x64-linux
            system: ubuntu-latest
            mono: "mono"
    runs-on: ${{ matrix.system }}
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      VCPKG_USER: rioki
      VCPKG_FEED_URL: https://nuget.pkg.github.com/rioki/index.json
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install CMake
      uses: lukka/get-cmake@latest
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: c01dc6ea7353758f2ed70df0bc29c97dfc650b3a
    - name: 'Setup NuGet/Vcpkg Credentials'
      shell: 'bash'
      run: |
        NUGET=$("$RUNVCPKG_VCPKG_ROOT/vcpkg" fetch nuget | tail -n 1)
        ${{ matrix.mono }} "$NUGET" sources add -source "${{env.VCPKG_FEED_URL}}" -storepasswordincleartext -name "GitHub" -username "${{env.VCPKG_USER}}" -password "${{ secrets.VCPKG_PAT_TOKEN }}"
        ${{ matrix.mono }} "$NUGET" setapikey "${{ secrets.VCPKG_PAT_TOKEN }}" -source "${{env.VCPKG_FEED_URL}}"
    - name: Build Debug
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-debug'
        buildPreset: 'ninja-debug'
    - name: Build Release
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-release'
        buildPreset: 'ninja-release'
